spring:
  datasource:
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: false

  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
    open-in-view: false
    show-sql: false
  main:
    banner-mode: off
    allow-bean-definition-overriding: true

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080
  servlet:
    context-path: ${CONTEXT_PATH}

#springdoc:
#  api-docs:
#    enabled: true
#    path: /swagger/docs
#  swagger-ui:
#    path: /swagger/index.html

jwt:
  secret: ${SPRING_JWT_SECRET}
  hash:
    secret: ${SPRING_JWT_HASH_SECRET}

services:
  telegram: ${TELEGRAM_URL}
  workspace: ${WORKSPACE_URL}
  channel: ${CHANNEL_URL}
  security: http://security-api:8080/api
#  workspace-api: ${WORKSPACE_API}