-- Проверка и создание таблицы DATABASECHANGELOG если она отсутствует
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_tables WHERE tablename = 'databasechangelog') THEN
        CREATE TABLE DATABASECHANGELOG (
            ID VARCHAR(255) NOT NULL,
            AUTHOR VARCHAR(255) NOT NULL,
            FILENAME VARCHAR(255) NOT NULL,
            DATEEXECUTED TIMESTAMP WITHOUT TIME ZONE NOT NULL,
            ORDEREXECUTED INT NOT NULL,
            EXECTYPE VARCHAR(10) NOT NULL,
            MD5SUM VARCHAR(50),
            DESCRIPTION VARCHAR(255),
            COMMENTS VARCHAR(255),
            TAG VARCHAR(255),
            LIQUIBASE VARCHAR(20),
            CONTEXTS VARCHAR(255),
            LABELS VARCHAR(255),
            DEPLOYMENT_ID VARCHAR(50)
        );
        
        CREATE TABLE DATABASECHANGELOGLOCK (
            ID INT NOT NULL,
            LOCKED BOOLEAN NOT NULL,
            LOCKGRANTED TIMESTAMP WITHOUT TIME ZONE,
            LOCKEDBY VARCHAR(255),
            CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID)
        );
        
        INSERT INTO DATABASECHANGELOGLOCK VALUES (1, FALSE, NULL, NULL);
    END IF;
END
$$; 